name: Auto-update pre-commit config
description: Run pre-commit autoupdate and upload config file as artifact

inputs:
  python-version:
    description: Python version to run pre-commit with
    default: "3.9"
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        source $HOME/.cargo/env
      shell: bash
    - run: uv pip install --color=always --system pre-commit
      shell: bash
    - run: pre-commit autoupdate --color=always
      shell: bash
    - run: git diff --color --unified=0
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: pre-commit
        path: .pre-commit-config.yaml
