name: Auto-update pre-commit config
description: Run pre-commit autoupdate and upload config file as artifact

inputs:
  python-version:
    description: Python version to run pre-commit with
    default: "3.12"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - uses: astral-sh/setup-uv@v5
    - env:
        FORCE_COLOR: True
        UV_SYSTEM_PYTHON: True
      run: uvx --with pre-commit-uv pre-commit autoupdate -j$(nproc)
      shell: bash
    - name: Show changes
      run: git diff --color --unified=0
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        include-hidden-files: true
        name: pre-commit
        path: .pre-commit-config.yaml
