name: Auto-update pre-commit config
description: Run pre-commit autoupdate and upload config file as artifact

inputs:
  python-version:
    description: Python version to run pre-commit with
    default: "3.9"
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - run: pip install pre-commit
      shell: bash
      env:
        TERM: xterm-256color
    - run: pre-commit autoupdate
      shell: bash
      env:
        TERM: xterm-256color
    - uses: actions/upload-artifact@v4
      with:
        name: pre-commit
        path: .pre-commit-config.yaml
